import './globals.css'
import { Inter } from 'next/font/google'
 

export const metadata = {
  title: 'Himal Portfolio',
  description: 'Generated by Himal Portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}  >{children}</body>
    </html>
  )
}
